# 같은 함수 내 비슷한 로직 실행 시 변수 헷갈리는 문제 구조적 개선

아래 형식으로 코드를 짰는데, 두 번째 for문 안에서 if블록 내 선언된 변수인 revStack에 대해서 연산을 한다는 것이 외부 영역의 변수인 stack의 변수를 조작하는 형태로 코드 처리를 해서 한참을 헤맸음.

물론 내 부주의도 있겠지만, 애초에 구조적인 방지 방법이 필요할 것으로 보임.

어떻게 이런 문제를 방지할 수 있을까 생각해보았는데, 별도의 함수로 추출해서 하나의 스코프에서는 하나의 변수명만 생각하는 것이 좋을 듯 하다.

실수할 여지 자체를 인지적으로 고려할 범위를 줄이는 형태로 줄이는 것이 좋지 않을까.

같은 변수명을 사용해도 문제가 없다.

음 근데 어쨌든 외부함수와 겹치는 변수명이 존재하는데 내부함수 안에서 선언된 로컬변수명이 문제없이 실행되는 건 어떤 원리인지 모르겠음. 궁금하네. 찾아보자.

```javascript
var minRemoveToMakeValid = function (s) {
  let result = "";
  const stack = [];

  for (const ch of s) {
    // 로직
  }

  // 특정 조건에서 비슷한 로직 재수행
  if (stack.length) {
    // let finalResult = "";
    // const revStack = [];

    // for (const ch of result) {
    //   // 로직
    // }

    // result = finalResult;
    // 별도의 스코프를 생성해서 해당 스코프에서 필요한 것만 인지적으로 고려할 수 있도록 구조를 개선
    result = removeReverse(result);
  }

  return result;
};

// if문의 로직을 별도 함수로 추출해서 호출했으면 더 좋았을 듯.
function removeReverse(s) {
  let result = "";
  const stack = [];

  for (const ch of s) {
  }

  return result;
}
```

# 외부함수의 변수와 내부함수의 변수명이 겹쳐도 괜찮은 이유?

함수 내 비슷한 로직 수행 시 헷갈릴 소지 자체를 없애기 위해서 함수로 분리하는 처리를 하였다.

그런데, 헷갈림 방지를 위해서 let으로 선언한 변수명을 동일하게 하였는데(stack, result) 이 경우에 outerfunction 의 변수 이름과 겹쳐도 잘 실행되는 이유가 뭔지 모르겠음.

코드 예시

```javascript
function outerfunc() {
  let result = "";

  innerfunc(); // 이 함수에서 let으로 동일하게 result로 선언된 변수가 해당 함수 내에 선언된 변수를 참조하는 이유가? outerfunction의 scope안에 있으니까 outerfunction 스코프에 선언된 result변수도 참조할 수 있는 상태일텐데
}

function innerfunc() {
  let result = "";
}
```

찾아본 결과 JavaScript는 변수를 현재 위치한 scope에서 참조가능한지 확인 후에 outer scope로 이동해서 또 찾고 이동하고 찾고 최종적으로는 Global scope까지 검색하는 형태로 동작한다고 한다.

그렇기 때문에 innerfunc에서 result라는 변수를 참조할 때, 먼저 innerfunc의 scope에서 변수를 탐색한다. 그래서 변수명이 겹쳐도 의도한대로 동작할 수 있음.

innerfunc의 같은 이름의 변수가 outerfunc의 해당 이름을 가지는 변수를 덮는 것처럼 보이는 현상을 variable shadowing이라고 한다고 하네.

그리고 variable shadowing은 헷갈리는 코드 작성으로 이어질 가능성이 높기 때문에 지양하는 것이 좋아 보인다.

# 재귀함수 return

```javascript
// 재귀함수에서 return을 하지 않는 케이스가 존재할 때 왜 문제가 되는지?
function t(arr) {
  console.log(arr);
  if (!arr.length) return arr;

  const temp = [...arr];
  temp.pop();

  t(temp); // 재귀적으로 호출한 함수의 처리 결과를 return해야지 최종적으로 return이 됨.
  // return t(temp);
}

console.log(t([5, 4, 3, 2, 1])); // undefined
```

잠깐 생각했을 때, 종료조건에 대해서만 값을 return하면 되지 않나라고 생각했는데 undefined가 반환되는 문제를 겪음.

보이는대로 판단하고 흐름을 보지 못한게 문제다.

마지막으로 실행되는 건 t([])가 아니라, t([5,4,3,2,1]) 이다.

`요소 5개 t 실행 -> 4개 실행 -> 3개 실행 -> 2개 실행 -> 1개 실행 -> -> 0개 실행 -> 0개 종료, [] 반환 -> 1개 종료, 반환값 없음. -> 2개 종료 반환값 없음.  -> 3개 종료 반환값 없음.  -> 4개 종료 반환값 없음.  -> 5개 종료 반환값 없음. `

실행 흐름이 위와 같기 때문에, 재귀적으로 호출되는 함수 결과값을 return하지 않으면 종료조건에 해당되는 함수를 호출하는 함수 안에서 말고는 return값이 없게 된다.

호출한 함수에서 결과값을 처리하기 위해서는 호출된 함수에서 return으로 값을 넘겨주는 처리가 필요함

위 흐름에서 아래 흐름으로 변경되어야 한다.

`요소 5개 t 실행 -> 4개 실행 -> 3개 실행 -> 2개 실행 -> 1개 실행 -> -> 0개 실행 -> 0개 종료, [] 반환 -> 1개 종료, 0개로 호출한 함수 반환값인 [] 반환 -> 2개 1개로 호출한 함수 반환값인 [] 반환  -> 3개 종료 2개로 호출한 함수 반환값인 [] 반환  -> 4개 종료 3개로 호출한 함수 반환값인 [] 반환  -> 5개 종료 4개로 호출한 함수 반환값인 [] 반환`

그렇구나. 재귀함수 사용할 때는 함수 실행 흐름에 대해서 잘 생각해야 한다.

